[bugfix] Fix applying erf function
- std::erf function does not support _Float16
- Fix by casting temporally

Resolves:
error: call of overloaded ‘erf(_Float16&)’ is ambiguous
 3394 |     auto f = [](_FP16 in) { return std::erf(in); };
      |                                    ~~~~~~~~^~~~

**Self evaluation:**
1. Build test:     [X]Passed [ ]Failed [ ]Skipped
2. Run test:     [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: skykongkong8 <ss.kong@samsung.com>